const dayjs = require('dayjs');

const generateDueDate = (daysAgo) => {
  return dayjs().add(-daysAgo, 'd').endOf('day');
};

module.exports = Object.freeze({
  CALENDAR_INITIAL_EVENTS: [
    {
      title: 'Product call',
      theme: 'GREEN',
      startTime: dayjs().add(-12, 'd').startOf('day'),
      endTime: dayjs().add(-12, 'd').endOf('day'),
    },
    {
      title: 'Meeting with tech team',
      theme: 'PINK',
      startTime: dayjs().add(-8, 'd').startOf('day'),
      endTime: dayjs().add(-8, 'd').endOf('day'),
    },
    {
      title: 'Meeting with Cristina',
      theme: 'PURPLE',
      startTime: dayjs().add(-2, 'd').startOf('day'),
      endTime: dayjs().add(-2, 'd').endOf('day'),
    },
    { title: 'Meeting with Alex', theme: 'BLUE', startTime: dayjs().startOf('day'), endTime: dayjs().endOf('day') },
    { title: 'Product Call', theme: 'GREEN', startTime: dayjs().startOf('day'), endTime: dayjs().endOf('day') },
    { title: 'Client Meeting', theme: 'PURPLE', startTime: dayjs().startOf('day'), endTime: dayjs().endOf('day') },
    {
      title: 'Client Meeting',
      theme: 'ORANGE',
      startTime: dayjs().add(3, 'd').startOf('day'),
      endTime: dayjs().add(3, 'd').endOf('day'),
    },
    {
      title: 'Product meeting',
      theme: 'PINK',
      startTime: dayjs().add(5, 'd').startOf('day'),
      endTime: dayjs().add(5, 'd').endOf('day'),
    },
    {
      title: 'Sales Meeting',
      theme: 'GREEN',
      startTime: dayjs().add(8, 'd').startOf('day'),
      endTime: dayjs().add(8, 'd').endOf('day'),
    },
    {
      title: 'Product Meeting',
      theme: 'ORANGE',
      startTime: dayjs().add(8, 'd').startOf('day'),
      endTime: dayjs().add(8, 'd').endOf('day'),
    },
    {
      title: 'Marketing Meeting',
      theme: 'PINK',
      startTime: dayjs().add(8, 'd').startOf('day'),
      endTime: dayjs().add(8, 'd').endOf('day'),
    },
    {
      title: 'Client Meeting',
      theme: 'GREEN',
      startTime: dayjs().add(8, 'd').startOf('day'),
      endTime: dayjs().add(8, 'd').endOf('day'),
    },
    {
      title: 'Sales meeting',
      theme: 'BLUE',
      startTime: dayjs().add(12, 'd').startOf('day'),
      endTime: dayjs().add(12, 'd').endOf('day'),
    },
    {
      title: 'Client meeting',
      theme: 'PURPLE',
      startTime: dayjs().add(16, 'd').startOf('day'),
      endTime: dayjs().add(16, 'd').endOf('day'),
    },
  ],

  RECENT_PROGRAMS: [
    {
      id: '1',
      Organization: 'Heirs Tech',
      Course: 'Frontend Development',
      Status: 'In Progress',
      amount: 100,
      DUE_DATE: dayjs().endOf('day'),
      progress: 75,
    },
    {
      id: '2',
      Organization: 'Africa Prudential',
      Course: 'Backend Development',
      Status: 'In Review',
      DUE_DATE: dayjs().add(-1, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '3',
      Organization: 'United Capital',
      Course: 'Product design',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-1, 'd').endOf('day'),
      progress: 70,
    },
    {
      id: '4',
      Organization: 'United Capital',
      Course: 'Product Management',
      Status: 'Completed',
      DUE_DATE: dayjs().add(-1, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '5',
      Organization: 'Transcorp',
      Course: 'Data Analysis',
      Status: 'In Review',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '6',
      Organization: 'Heirs Holding',
      Course: 'Devops',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 75,
    },
    {
      id: '7',
      Organization: 'I-Academy',
      Course: 'Cybersecurity',
      Status: 'Completed',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '8',
      Organization: 'UBA',
      Course: 'AI Engineering',
      Status: 'In Review',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '9',
      Organization: 'Access Bank',
      Course: 'Software Development',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 50,
    },
    {
      id: '10',
      Organization: 'Heirs Holding',
      Course: 'Full-Stack Development',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-2, 'd').endOf('day'),
      progress: 40,
    },
    {
      id: '11',
      Organization: 'UBA',
      Course: 'AI Engineering',
      Status: 'Completed',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '12',
      Organization: 'Africa Prudential',
      Course: 'Backend Development',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 20,
    },
    {
      id: '13',
      Organization: 'I-Academy',
      Course: 'Data  Analysis',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 75,
    },
    {
      id: '14',
      Organization: 'FLutterWave',
      Course: 'Cybersecurity',
      Status: 'In Review',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '15',
      Organization: 'Red Tech',
      Course: 'Information Security',
      Status: 'In Progress',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 35,
    },
    {
      id: '16',
      Organization: 'I-Academy',
      Course: 'Frontend Development',
      Status: 'Completed',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '17',
      Organization: 'UBA',
      Course: 'Cybersecurity',
      Status: 'In Review',
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 100,
    },
    {
      id: '18',
      Organization: 'Heirs Holding',
      Course: 'Cybersecurity',
      Status: 'In Progress',
      amount: 151,
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 80,
    },
    {
      id: '19',
      Organization: 'I-Academy',
      Course: 'Product Management',
      Status: 'In Progress',
      amount: 617,
      DUE_DATE: dayjs().add(-3, 'd').endOf('day'),
      progress: 75,
    },
  ],

  USER_INFO: [
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/493.jpg',
      user: 'Virginia Mertz',
      userType: 'Tutor',
      program: 'Software Engineering',
      cohort: "O'Reilly Inc",
      Status: 'Active',
      lastLogin: '2023-12-30T13:40:33.691Z',
      gender: 'male',
      id: '1',
      email: 'virginia.mertz@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1990-05-15',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/9.jpg',
      user: 'Sidney Weissnat',
      userType: 'Student',
      program: 'Data Science',
      cohort: 'Glover Inc',
      Status: 'Disabled',
      lastLogin: '2023-03-27T06:54:27.249Z',
      gender: 'male',
      id: '2',
      email: 'sidney.weissnat@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'New York',
      dateOfBirth: '1995-08-20',
      levelOfExperience: 'Beginner',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1001.jpg',
      user: 'Dr. Mack Reichel DDS',
      userType: 'Student',
      program: 'Cybersecurity',
      cohort: 'Gleichner - Schneider',
      Status: 'Active',
      lastLogin: '2023-03-04T20:41:38.010Z',
      gender: 'female',
      id: '3',
      email: 'mack.reichel@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Texas',
      dateOfBirth: '1988-11-10',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/433.jpg',
      user: 'Mrs. Lana Waters',
      userType: 'Student',
      program: 'Artificial Intelligence',
      cohort: 'Turner LLC',
      Status: 'Disabled',
      lastLogin: '2023-08-03T08:59:20.798Z',
      gender: 'female',
      id: '4',
      email: 'lana.waters@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Florida',
      dateOfBirth: '1975-09-25',
      levelOfExperience: 'Advanced',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/366.jpg',
      user: 'Ana Kshlerin',
      userType: 'Tutor',
      program: 'Web Development',
      cohort: "Keeling, O'Keefe and Beatty",
      Status: 'Active',
      lastLogin: '2023-03-25T21:03:11.654Z',
      gender: 'female',
      id: '5',
      email: 'ana.kshlerin@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1983-07-12',
      levelOfExperience: 'Expert',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/664.jpg',
      user: 'Patricia Tillman',
      userType: 'Student',
      program: 'Machine Learning',
      cohort: 'Rohan - Wintheiser',
      Status: 'Active',
      lastLogin: '2023-09-17T18:08:19.958Z',
      gender: 'female',
      id: '6',
      email: 'patricia.tillman@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Washington',
      dateOfBirth: '1980-02-28',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/218.jpg',
      user: 'Clayton Volkman',
      userType: 'Student',
      program: 'Data Analytics',
      cohort: 'Connelly - Keeling',
      Status: 'Disabled',
      lastLogin: '2023-10-04T10:37:07.649Z',
      gender: 'female',
      id: '7',
      email: 'clayton.volkman@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Illinois',
      dateOfBirth: '1992-11-15',
      levelOfExperience: 'Advanced',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/166.jpg',
      user: 'Scott Dibbert',
      userType: 'Tutor',
      program: 'Cybersecurity',
      cohort: 'Schultz, Pollich and Dickinson',
      Status: 'Active',
      lastLogin: '2024-02-16T23:22:44.487Z',
      gender: 'male',
      id: '8',
      email: 'scott.dibbert@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Texas',
      dateOfBirth: '1985-06-20',
      levelOfExperience: 'Expert',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/525.jpg',
      user: 'Jeanne Kemmer',
      userType: 'Student',
      program: 'Web Development',
      cohort: 'Erdman - Rosenbaum',
      Status: 'Active',
      lastLogin: '2023-11-26T20:29:15.552Z',
      gender: 'male',
      id: '9',
      email: 'jeanne.kemmer@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1987-09-08',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/696.jpg',
      user: 'Kari Heathcote',
      userType: 'Tutor',
      program: 'Artificial Intelligence',
      cohort: 'Schmeler - Bartell',
      Status: 'Active',
      lastLogin: '2023-04-11T04:59:34.288Z',
      gender: 'male',
      id: '10',
      email: 'kari.heathcote@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Washington',
      dateOfBirth: '1986-12-03',
      levelOfExperience: 'Expert',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/373.jpg',
      user: 'Preston Pfannerstill',
      userType: 'Tutor',
      program: 'Data Science',
      cohort: 'Kertzmann - Boyer',
      Status: 'Disabled',
      lastLogin: '2023-07-12T03:10:24.938Z',
      gender: 'male',
      id: '11',
      email: 'preston.pfannerstill@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'New York',
      dateOfBirth: '1984-03-18',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/931.jpg',
      user: 'Glenda Sipes',
      userType: 'Student',
      program: 'Web Development',
      cohort: 'Mayert - Grady',
      Status: 'Active',
      lastLogin: '2023-10-13T03:23:41.710Z',
      gender: 'male',
      id: '12',
      email: 'glenda.sipes@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1996-01-25',
      levelOfExperience: 'Beginner',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1034.jpg',
      user: 'Mrs. Tina Fadel',
      userType: 'Tutor',
      program: 'Software Engineering',
      cohort: 'Marks, Denesik and Stanton',
      Status: 'Disabled',
      lastLogin: '2024-02-09T22:52:39.376Z',
      gender: 'male',
      id: '13',
      email: 'tina.fadel@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1978-08-10',
      levelOfExperience: 'Advanced',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/303.jpg',
      user: 'Sherri Connelly',
      userType: 'Student',
      program: 'Machine Learning',
      cohort: 'Huels - Simonis',
      Status: 'Active',
      lastLogin: '2023-09-02T05:58:56.050Z',
      gender: 'female',
      id: '14',
      email: 'sherri.connelly@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Texas',
      dateOfBirth: '1989-04-30',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/955.jpg',
      user: 'Wm Medhurst',
      userType: 'Tutor',
      program: 'Data Analytics',
      cohort: 'Leffler - Walker',
      Status: 'Active',
      lastLogin: '2023-06-20T11:09:24.374Z',
      gender: 'male',
      id: '15',
      email: 'wm.medhurst@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Texas',
      dateOfBirth: '1982-12-15',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/390.jpg',
      user: 'Tiffany Lind',
      userType: 'Student',
      program: 'Artificial Intelligence',
      cohort: 'Macejkovic - Ferry',
      Status: 'Active',
      lastLogin: '2023-07-27T18:56:05.579Z',
      gender: 'female',
      id: '16',
      email: 'tiffany.lind@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1993-06-05',
      levelOfExperience: 'Advanced',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/983.jpg',
      user: 'Dr. Dawn Gusikowski',
      userType: 'Student',
      program: 'Web Development',
      cohort: 'Kuphal - Hirthe',
      Status: 'Disabled',
      lastLogin: '2023-04-11T19:22:37.402Z',
      gender: 'female',
      id: '17',
      email: 'dawn.gusikowski@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'Washington',
      dateOfBirth: '1997-11-20',
      levelOfExperience: 'Beginner',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/47.jpg',
      user: 'Irene Mosciski',
      userType: 'Student',
      program: 'Data Science',
      cohort: 'Hansen - MacGyver',
      Status: 'Active',
      lastLogin: '2023-10-15T02:01:21.342Z',
      gender: 'male',
      id: '18',
      email: 'irene.mosciski@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'New York',
      dateOfBirth: '1986-03-12',
      levelOfExperience: 'Intermediate',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1249.jpg',
      user: 'Mrs. Charlene Baumbach',
      userType: 'Tutor',
      program: 'Cybersecurity',
      cohort: 'Kuhn and Sons',
      Status: 'Active',
      lastLogin: '2023-04-26T04:05:37.621Z',
      gender: 'male',
      id: '19',
      email: 'charlene.baumbach@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1981-09-18',
      levelOfExperience: 'Expert',
    },
    {
      avatar: 'https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/166.jpg',
      user: 'Alexis Reichert',
      userType: 'Tutor',
      program: 'Software Engineering',
      cohort: 'Will, Rau and Connelly',
      Status: 'Disabled',
      lastLogin: '2023-04-09T17:14:11.701Z',
      gender: 'female',
      id: '20',
      email: 'alexis.reichert@example.com',
      phoneNumber: '+1234567890',
      countryOfResidence: 'United States',
      stateOfResidence: 'California',
      dateOfBirth: '1980-05-03',
      levelOfExperience: 'Expert',
    },
  ],
});
