module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: 'USER_DETAIL',
    LEAD_ADD_NEW: 'LEAD_ADD_NEW',
    ADMIN_ADD_NEW: 'ADMIN_ADD_NEW',
    COHORT_ADD_NEW: 'COHORT_ADD_NEW',
    PROGRAM_ADD_NEW: 'PROGRAM_ADD_NEW',
    COURSE_ADD_NEW: 'COURSE_ADD_NEW',
    LIVE_CLASSES_ADD_NEW: 'LIVE_CLASSES_ADD_NEW',
    VERIFICATION_ADD_NEW: 'VERIFICATION_ADD_NEW',
    ADMISSION_ADD_NEW: 'ADMISSION_ADD_NEW',
    ROLES_AND_PERMISSIONS_ADD_NEW: 'ROLES_AND_PERMISSIONS_ADD_NEW',
    CONFIRMATION: 'CONFIRMATION',
    RESUME_VIEW: 'RESUME_VIEW',
    UNAUTHORIZED: 'UNAUTHORIZED',
    DEFAULT: '',
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: 'NOTIFICATION',
    CALENDAR_EVENTS: 'CALENDAR_EVENTS',
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: 'LEAD_DELETE',
    ADMIN_DELETE: 'ADMIN_DELETE',
    COHORT_DELETE: 'COHORT_DELETE',
    PROGRAM_DELETE: 'PROGRAM_DELETE',
    COURSE_DELETE: 'COURSE_DELETE',
    LIVE_CLASSES_DELETE: 'LIVE_CLASSES_DELETE',
    VERIFICATION_DELETE: 'VERIFICATION_DELETE',
    ADMISSION_DELETE: 'ADMISSION_DELETE',
    ROLES_AND_PERMISSIONS_DELETE: 'ROLES_AND_PERMISSIONS_DELETE',
    RESUME_VIEW_CLOSE: 'RESUME_VIEW_CLOSE',
    UNAUTHORIZED_CLOSE: 'UNAUTHORIZED_CLOSE'
  },
});
